name: Run Bloxd.io Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install selenium webdriver-manager

      - name: Run Bot
        run: python bot.py
